### PR TITLE
What's wrong with travis MKL?

### PR DESCRIPTION
**Pull request by mbillingr**
see #107

### CODE REVIEW

**Comment by cle1109** [comment]
Do you know why there are 2 Travis build jobs (pr and push)?

**Comment by mbillingr** [comment]
I do not know, but I guess that is because the branch exists in the main repository. So it starts one build because I pushed to a branch in this repo, and another build because it's included in a pull request.

**Comment by mbillingr** [comment]
Didn't change anything. I hope this is just a passing issue with the anaconda packages ...

**Comment by cle1109** [comment]
Yep. It's not the first time that Travis is having strange hiccups. Is this worth opening an issue at https://github.com/travis-ci/travis-ci?

**Comment by mbillingr** [comment]
I don't think the problem is related to travis. Seems more like an anaconda problem.

**Comment by cle1109** [comment]
Can you try to commit something and see if it works now?

**Comment by cle1109** [comment]
Only the first env is working - is it because Fortran is installed? Strange that we get MKL-related errors even though we explicitly uninstall all MKL-related Anaconda packages.

**Comment by mbillingr** [comment]
I have no idea :)

**Comment by mbillingr** [comment]
Although we explicitly uninstall mkl, it is reinstalled again...

**Comment by mbillingr** [comment]
The installation **with** MKL works now.

The installation **without** MKL does not work.
- Although we do not explicitly request it, MKL is installed along with other packages
- Although MKL is installed, it does not appear to be used (there is no message about the trial period).
- Although MKL is not used, we get the error: `Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.`

@cle1109 Any ideas?

**Pull request closed without merging**
