### PR TITLE
Codecov: Removed suggestions

### PR DESCRIPTION
**Pull request by mbillingr**
> @mbillingr can you try disabling suggestions in codecov.yml line 22?

@cbrnr OK. Why?

### CODE REVIEW

**Comment by cbrnr** [comment]
I was wondering if the comment could be made more compact somehow. Obviously, removing suggestions didn't change anything. Do you know if the format of the comment can be changed somehow? In particular, the last 2 lines below the table could be removed.

**Comment by mbillingr** [comment]
Maybe it *used* to look like that?

I think the configuration applies only to the verbatim part of the post.

**Comment by cbrnr** [comment]
Maybe. Can you try to change some parameters in this line to see if it has any effect?

**Comment by cbrnr** [comment]
So... why is the coverage check not shown?

**Comment by mbillingr** [comment]
because argh!?

**Comment by cbrnr** [comment]
Either it's a problem with GitHub, or Codecov is not really better than Coveralls...

**Comment by cbrnr** [comment]
Also, if this ever works, maybe this is a nice plugin: https://github.com/codecov/browser-extension#codecov-extension

**Comment by mbillingr** [comment]
The browser extension works nicely. I don't know how it's done, but if I browse to a source file in the master branch I get nice green/yellow/red line backgrounds

**Comment by mbillingr** [comment]
Apparently, codecov did not like the empty layout format string.
And, apparently it does not update the comment if the coverage does not change...

**Comment by cbrnr** [comment]
Since you've created a separate repo for testing such issues, I'm closing this one.

**Pull request closed without merging**
