### PR TITLE
Improve coding style

### LINKED ISSUE #79: Coding style
We should try to adhere to a consistent coding style. I suggest we stick to what everyone else does, namely PEP8 and NumPy docstrings, such as scikit-learn (that's where I mainly look up style-related things if in doubt).

If you agree, I will create a PR after we're done with #65, the big one.

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #79. @mbillingr can you confirm if it is OK to move the `cat_trials` import outside of the function?

### CODE REVIEW

**Comment by mbillingr** [comment]
Yes, that is OK. In fact, you could also move the `dot_special` import outside. 

In principle, we could move all local imports and the scipy import outside. The local imports are available anyway, and scipy is a obligatory dependency of scot. Only `sklearn` is optional and should remain inside the function.

**Comment by cle1109** [comment]
@mbillingr I've changed the input argument order in some functions. Could you please check if this is OK, or are we unnecessarily breaking the API? I thought the new order makes more sense.

**Comment by cle1109** [comment]
Hmmmm. Seems like rebasing didn't work as expected. Again.

**Comment by mbillingr** [comment]
Did you pull/push in pycharm? :p

I think, what I did was to reset `HEAD` to the last good commit. I think in this case the commit is `Fix tests` (f7a3f7f)

Note that after doing a rebase your local branch and the branch at origin will have diverged. You *must not* merge this diverged branches. Instead use `push --force` to overwrite the old commits at origin.

**Comment by cle1109** [comment]
OK, that did it. I should do all git-related stuff on the command line. Although I'm sure there's an option in PyCharm that I need to check in order to perform a rebase correctly.

I think I'm going to revert the changed argument order. The statistics example produces different results.

**Comment by mbillingr** [comment]
The problem with changing the argument order is that you will never know for sure if you found all the places where the function is used.

**Comment by cle1109** [comment]
Agreed. That's why I reverted it.

**Comment by mbillingr** [comment]
@cle1109 can you rebase this branch to the current master?

**Comment by cle1109** [comment]
Looks like rebasing in PyCharm worked this time - I had to enable Force Push in the settings.

**Comment by mbillingr** [comment]
Force push is also what you have to do after a rebase in the console.

But I still don't trust PyCharm :)

**Comment by cle1109** [comment]
Yes, it still feels like it could do all sorts of weird stuff in the background, but so far it seems to be working. Most of the time, I'm just too lazy to open a terminal to rebase and force push. And BTW, PyCharm has a menu entry for "rebase my GitHub fork" which has worked for me so far.

**Comment by cbrnr** [comment]
@mbillingr could you please check if the changes are OK? If yes, please merge it - I want to avoid blowing up this PR more, because this means a lot of manual merging when rebasing. We can continue to improve the code style in another PR.

**Pull request merged**
