### PR TITLE
Use new-style classes

### PR DESCRIPTION
**Pull request by cle1109**
Use new-style classes, addresses #41.

### CODE REVIEW

**Comment by kazemakase** [comment]
Where do all the whitespace changes come from?

**Comment by cle1109** [comment]
Hm, I didn't notice those. Probably PyCharm's PEP8 correction or something. I think spaces on empty lines are [discouraged](http://stackoverflow.com/questions/2727988/python-indentation-in-empty-lines).

**Comment by kazemakase** [comment]
There doesn't seem to be any consensus, but I don't really care about blank lines. They  just make it hard to see the actual changes in the diff.

**Comment by cle1109** [comment]
I agree. Since PyCharm does it this way by default, I'd say we simply adopt this style.

**Comment by kazemakase** [comment]
Strange that It did not do it by default when I wrote that code...

**Comment by kazemakase** [comment]
By the way, I think you can merge this PR anytime.

**Pull request merged**
