### PR TITLE
New configuration system

### PR DESCRIPTION
**Pull request by mbillingr**
Discussion: #69

This PR became rather big, because I had to change the backend mechanism which was closely tied to the old configuration system.

Currently two options are supported:

    [scot]
    verbose = True/False
    backend = builtin/sklearn

### CODE REVIEW

**Comment by kazemakase** [comment]
Doh. Looks like the ConfigurationParser is not the same in Py2 and Py3.

**Comment by cle1109** [comment]
Can you access the config with arguments in both 2 and 3 (as described [here](http://stackoverflow.com/questions/16407329/python-configparser-attributeerror-configparser-instance-has-no-attribute)?

**Comment by mbillingr** [comment]
rebased to master

**Comment by mbillingr** [comment]
@cle1109 Any objections to merging this?

**Pull request merged**
