### PR TITLE
Data (down)loader

### PR DESCRIPTION
**Pull request by mbillingr**
This PR deals with moving example data downloads from scot-data to scot. Previous discussion: scot-dev/scot-data#1.

Currently the PR only contains a first draft of the interface, which is open for discussion.

cc @cle1109

### CODE REVIEW

**Comment by kazemakase** [comment]
@agramfort We are currently discussing an automated downloader for example data. We don't want to inconvenience the user by putting downloads in arbitrary locations without them knowing. Do you have default locations for example data in MNE, or do you always ask the user where to put it?

**Comment by agramfort** [comment]
in MNE we put datasets in examples folder for historical reasons but if
this folder is not readable we put in ~/mne_data. You can specify it with
an environ variable MNE_DATA

**Comment by kazemakase** [comment]
Thank you @agramfort for your input.
Putting the data directly under the home folder seems to be the best solution so far... We could also make it a configurable default.

**Comment by cle1109** [comment]
I kind of like the idea of having a `download` flag, which is `False` by default. The function interface could look like this:

    def load(dataset, download=False, datadir="~/scot_data"):

`download` could be `True`, `False`, and `"auto"` - the latter automatically downloads the file if it is not already in the specified location.

**Comment by kazemakase** [comment]
I'm concerned with the use case of somebody trying out scot. What they likely want do is downloading the package and running an example.

If the default is not to donwload the example will not run, the user gets annoyed, and they use sift instead of scot.

**Comment by cle1109** [comment]
Then set `download="auto"`? The question is then do we need this flag at all if you always want to download the file if it's not there? Probably not, then the only thing we have is the `datadir`. Sounds good to me.

**Comment by kazemakase** [comment]
Agreed. shall we use a portable version of `~/scot_data` as the default?

**Comment by cle1109** [comment]
Yes. Can you test if `~` is already portable? On Windows, this should point to the user's home directory `C:\Users\user`, so there is probably nothing to do there.

**Comment by kazemakase** [comment]
this works: 

    def load(dataset, datadir=os.path.expanduser("~/scot_data")):

**Comment by cle1109** [comment]
Cool - I guess we have our interface!

**Comment by cle1109** [comment]
@mbillingr, what's the status of this PR? Are we ready to get rid of the `scot-data` package and move the example data into the main `scot` package?

**Comment by mbillingr** [comment]
@cle1109 uh.. no.. I just realized we have only defined the interface, but it's totally lacking implementation.

Btw, I think the idea was to move only the loader into the `scot` package. The data itself should stay somewhere else so we don't carry a 50+MB data file around in the repository.

**Comment by cle1109** [comment]
Only moving the loader is fine as long as we get rid of the scot-data package. Any ideas where we could put the binary? Does GitHub offer such an option?

**Comment by cle1109** [comment]
Can we leave the data at https://github.com/scot-dev/scot-data/blob/master/scotdata/motorimagery.mat for now?

**Comment by mbillingr** [comment]
I think we can leave the binary in the repository and let the downloader fetch it from there.

If at some point in the future GitHub complains that we create too much traffic we can always look for another storage location.

**Pull request closed without merging**
