### PR TITLE
Nicer plot_topo

### PR DESCRIPTION
**Pull request by cbrnr**
Options for plotting the locations and the head (default plot both) and a nicer look by default (smaller electrode dots with transparency, thinner lines).

### CODE REVIEW

**Comment by cbrnr** [comment]
@mbillingr and once again our tests fail. Did we break anything or is it Travis, Anaconda or a combination?

**Comment by cbrnr** [comment]
And yes, in case you were wondering, all tests pass on my local machine.

**Comment by cbrnr** [comment]
See #173 for Travis issues

**Comment by mbillingr** [comment]
Hmm.. is there any sensible way of testing plotting functions other than trying to run the code and see if there are errors?

**Comment by cbrnr** [comment]
I can't think of something else, because we don't want to test for specific elements in the plot, do we?

**Comment by cbrnr** [comment]
@mbillingr OK for merge?

**Pull request merged**
