### PR TITLE
Fix warning about open windows in tests

### LINKED ISSUE #14: Matplotlib Figures
Replace `matplotlib.pyplot.figure()` with `matplotlib.figure.Figure()`.

This should allow for better garbage collection of unused figures?

### PR DESCRIPTION
**Pull request by mbillingr**
Fixes #14

### CODE REVIEW

**Comment by cle1109** [comment]
That seemed to have done the trick - Travis is happy. +1 for merging.

**Comment by mbillingr** [comment]
What?! I had not expected such a simple solution would work :)

**Comment by mbillingr** [comment]
Btw, what happened to the FastICA and Infomax warnings?

**Comment by cle1109** [comment]
No idea -  can you check where exactly they appeared in old Travis logs?

**Comment by mbillingr** [comment]
I still see them when running the tests locally. Let's continue this discussion in #97.

**Comment by cle1109** [comment]
Is there a reason why we didn't merge this PR?

**Comment by mbillingr** [comment]
I'm not sure if we actually fixed the problem or if the warnings disappeard due to another reason.

**Comment by cle1109** [comment]
The warning didn't disappear (see https://travis-ci.org/scot-dev/scot/jobs/107176594).

**Comment by mbillingr** [comment]
Oh, wait... Did I close this PR instead of merging it? That was an unintend accident :)

**Comment by cle1109** [comment]
Why do we get these MKL errors in Travis?

**Comment by mbillingr** [comment]
I don't know. They only popped up recently. 

Conda seems to install MKL. Our install script tries to remove MKL, but this does not seem to work suddenly. Or maybe it works and that's why it can't be loaded...

**Comment by cle1109** [comment]
Not good. Anyway, this PR has only one added line of code. Could you please go ahead and merge it with master?

**Pull request merged**
