### PR TITLE
Building the documentation on Windows

### PR DESCRIPTION
**Pull request by kazemakase**
Looks like I can get it to work.

### CODE REVIEW

**Comment by kazemakase** [comment]
Do you know where the documentation gets the scot version number from?

**Comment by cle1109** [comment]
No, I only ever built it, but never actually took a closer look at the sources...

**Comment by kazemakase** [comment]
I just realized it's hardcoded :(

**Comment by cle1109** [comment]
This sucks, but for the moments let's just keep it that way and hope we don't forget to update the version with every update of the docs.

**Comment by kazemakase** [comment]
No problem, I fixed this already :p

**Comment by cle1109** [comment]
:+1:

**Pull request merged**
