### PR TITLE
cut_segment now uses duck typing for indices

### PR DESCRIPTION
**Pull request by cle1109**
Addresses #87.

### CODE REVIEW

**Comment by mbillingr** [comment]
Let's add a test that checks if the function works correctly with arguments like 3.0 and if it correctly raises an error when passing arguments like 4.2.

**Comment by cle1109** [comment]
Should I introduce these changes also in our `transpose` branch?

**Comment by mbillingr** [comment]
No, if you meant to duplicate the changes.

Yes, if you meant to rebase the `transpose` branch to the current master.

**Comment by cle1109** [comment]
Well yes, we will have to rebase and resolve the merge conflict.

**Pull request merged**
