### PR TITLE
Fix MKL Error in Travis

### LINKED ISSUE #107: Travis setups require MKL?
Two of our three Travis setups fail because some MKL-related libs are not found. However, we've explicitly specified `INSTALL_MKL="false"` in all of our setups. It only works in the first setup (Python 2.7, latest packages).

### PR DESCRIPTION
**Pull request by mbillingr**
Closes #108
Closes #107

### CODE REVIEW

**Comment by cle1109** [comment]
Why is it working now?

**Comment by mbillingr** [comment]
I've increased numpy/scipy versions :)

**Comment by cle1109** [comment]
What? That's good news, but I wonder if we should create test environments that always fetch the latest package versions of Numpy, Scipy, scikit-learn, and matplotlib instead of relying on fixed version numbers that will stop working eventually... Anyway, thanks for fixing this one!

**Comment by mbillingr** [comment]
Normally it's the other way round - fixed versions are more stable because they are, well, fixed :)

Maybe I did't pay attention during the last upgrade, or maybe there is a hidden dependency that caused trouble.

**Pull request merged**
