### PR TITLE
Add keep_sources method

### PR DESCRIPTION
**Pull request by cle1109**
Addresses at least part of #141 (I didn't implement a mask yet).

### CODE REVIEW

**Comment by mbillingr** [comment]
Don't forget to add a test for this method.

Do you plan to add the mask in this PR too?

**Comment by cle1109** [comment]
I think we should add the mask in another PR.

Also offtopic: many tests need artificial test data (such as the tests I just wrote) - we should create a central facility that generates data for all tests. Once we move our real example data out of `scot-data`, we could then even write (optional) tests that work on the example data. What do you think?

**Comment by mbillingr** [comment]
I agree. In the beginning I intended to have such a central test data generation facility. There is a `generate_testdata.py` that does not do very much at the moment.

It would be awesome if we could get a realistic leadfield matrix from a head model to generate testing data.

**Comment by cle1109** [comment]
OK. I'll open a new issue.

Also, go ahead and merge this PR if you're happy with it.

**Pull request merged**
