### PR TITLE
Check and update Travis CI

### PR DESCRIPTION
**Pull request by mbillingr**
Does Travis have problems?

### CODE REVIEW

**Comment by mbillingr** [comment]
Seems to be working, here...

**Comment by mbillingr** [comment]
@cle1109 
With this PR tests are now performed against the newest versions of numpy, scipy, etc.

I've also added a test for older version of these libraries, so we can specify minimum requirements.

**Comment by cle1109** [comment]
Great - feel free to merge. BTW, what are our minimum requirements now? We could mention this in our docs.

**Comment by mbillingr** [comment]
It works with numpy 1.8.0, scipy 0.13.3, scikit-learn 0.15.0, and matplotlib 1.4.0 on Python 2.7.

We could probably go lower than that, but I think two releases behind current is good enough for the moment. I believe the gap will grow in the future ;)

**Comment by cle1109** [comment]
Very good, this sounds reasonable. Could you add these requirements somewhere? At least it should be added to `README.md`, and maybe adding it to the online doc would also be a good idea.

**Comment by mbillingr** [comment]
Feel free to merge if you're happy.

**Pull request merged**
