### PR TITLE
Set reducedim to None by default in Workspace

### LINKED ISSUE #148: cspvarica does not support relative (percent) reducedim
I noticed that in contrast to `mvarica` (which uses PCA), `cspvarica` does not support a relative number for `reducedim` (e.g. 0.99 to retain 99% of the variance). This is a problem because the `Workspace` sets the default value of `reducedim` to 0.99.

What do you suggest to do @mbillingr? I guess it is not possible to run `cspvarica` with a relative number for `reducedim?`

### PR DESCRIPTION
**Pull request by cle1109**
Fixes #148. Feel free to merge @mbillingr.

### CODE REVIEW

**Comment by mbillingr** [comment]
I think the test that fails relies on the old default reduction. We may have to set the value manually.

**Comment by mbillingr** [comment]
This time an unrelated test failed: #153.
I'll restart travis too see if it was a random problem.

**Comment by cle1109** [comment]
Interesting. It fails only on Python 3.5 (which works fine on my local machine). I'm losing faith in Travis...

**Comment by mbillingr** [comment]
I don't think it's travis' fault. It seems more like a random problem to me.

**Comment by cle1109** [comment]
It works now. However, it would be good to fix this behavior in #153. Feel free to merge this one.

**Pull request merged**
