### PR TITLE
Remove return values

### LINKED ISSUE #137: Do we need return values for do_mvarica and do_cspvarica?
I was wondering if we really need return values for the functions `do_mvarica` and `do_cspvarica`. Somehow, I expect these functions to store the computed values in the `Workspace` object (which they do) - so why do they need to return the results as well?

### PR DESCRIPTION
**Pull request by cle1109**
Resolves #137

### CODE REVIEW

**Comment by mbillingr** [comment]
Would it make sense to return `self` for operator chaining?

Btw, 'addresses' is no magic keyword :)

**Comment by cle1109** [comment]
> Would it make sense to return `self` for operator chaining?

Hm. It's pretty unlikely that someone would want to chain ICA, MVARICA, and CSPVARICA. But if it doesn't hurt - why not? Does anything get printed in an interactive session if we return `self`? I'd prefer if no output was produced.

> Btw, 'addresses' is no magic keyword :)

They should really add it.

**Comment by mbillingr** [comment]
> Hm. It's pretty unlikely that someone would want to chain ICA, MVARICA, and CSPVARICA

hehe, yes :)
But this would make sense: `ws.set_data(data).do_mvariaca().get_connectivity('PDC')`

> Does anything get printed in an interactive session if we return self? I'd prefer if no output was produced.

Uhm.. yes. I think it prints the return value :(

>> Btw, 'addresses' is no magic keyword :)

> They should really add it.

+1

**Comment by cle1109** [comment]
> But this would make sense: `ws.set_data(data).do_mvariaca().get_connectivity('PDC')`

Right, that's a pretty awesome use case. We should return self. Even though it prints the return value. Which is `Workspace.__str__` or `Workspace.__repr__`?

**Comment by mbillingr** [comment]
> Right, that's a pretty awesome use case. We should return self.

Do the other methods (such as `set_data`) return `self`? Maybe we should add it there too :)

> Which is Workspace.__str__ or Workspace.__repr__?

In IPython:
```
In [7]: class A:
   ...:     def __repr__(self):
   ...:         return('repr')
   ...:     def __str__(self):
   ...:         return('str')
   ...: 

In [8]: A()
Out[8]: repr
```

**Comment by cle1109** [comment]
> Do the other methods (such as `set_data`) return self? Maybe we should add it there too :)

+1. Where do you want to return `self`?

Yes! Since we decided in #124 that `__repr__` returns just a one-liner, this does not interfere too much with IPython output.

**Comment by mbillingr** [comment]
> Where do you want to return self?

`set_locations`, `set_premixing`, `set_data`, `set_used_labels`, `do_mvarica`, `do_cspvarica`, `do_ica`, `remove_sources`, `fit_var`, `optimize_var`

**Comment by cle1109** [comment]
All methods done. Can you also check if the docstring on the return value looks right?

**Comment by mbillingr** [comment]
More accuractely, the docstring would say "reference to the Workspace object".

But this is Python, and references are the default, so I don't think we have to be explicit here. If you agree feel free to merge.

**Pull request merged**
