### PR TITLE
make documentation buildable in 2024 :)

### PR DESCRIPTION
**Pull request by mbillingr**
I managed to build the documentation again! :partying_face: 

Various incompatibilities had to be fixed, but i am amazed how well it still works after 10 years.

### CODE REVIEW

**Comment by cbrnr** [comment]
Oh wow, thanks @mbillingr! Have you already updated the docs so that the jquery-related security issue is resolved? Are there any packages pinned, or does the build always use the latest available versions? And finally, why are the tests failing :laughing:?

**Comment by mbillingr** [comment]
> Have you already updated the docs so that the jquery-related security issue is resolved?

Yes, I've updated the doc pages but I don't know if this issue was resolved. Dependabot will tell us next week, I guess :)


> Are there any packages pinned, or does the build always use the latest available versions?

Nothing pinned. I just installed the newest version of each missing package. If there were any issues I tried to fix them in our sources. (Actually, I think I broke the LaTeX build but I don't see why we would need it anyway.) The closest thing we have to a pinned dependency is the numpydoc sphinx extension subrepository. I've upgraded it to the newest version without any problems, though.


>  And finally, why are the tests failing 😆?

No idea. They are failing for something I did not even touch in this PR... how annoying!

**Comment by cbrnr** [comment]
> Nothing pinned. I just installed the newest version of each missing package. If there were any issues I tried to fix them in our sources. (Actually, I think I broke the LaTeX build but I don't see why we would need it anyway.) The closest thing we have to a pinned dependency is the numpydoc sphinx extension subrepository. I've upgraded it to the newest version without any problems, though.

Can you maybe add a sentence on how to update packages to the instructions? Ideally, the instructions should be self-contained so that we can re-build the docs again in 2034!

> No idea. They are failing for something I did not even touch in this PR... how annoying!

:smile: That's not the first time I've seen this happen! How do you want to proceed? Do you have time to take a look? Or should we go ahead and merge with the failing tests :fearful:?

**Comment by mbillingr** [comment]
> Can you maybe add a sentence on how to update packages to the instructions?

I started with a fresh venv and did a `pip install` for whatever was raising an import error. Do you think that information would be useful in the documentation?


> 😄 That's not the first time I've seen this happen! How do you want to proceed? Do you have time to take a look? Or should we go ahead and merge with the failing tests 😨?

The bad news is that the tests are broken, but the good news is that the tests are broken. :)
I quickly checked. We are comparing floats for equality, which fails because of rounding errors. I can fix the failing test but I don't have the time to look for all comparisons.

**Comment by cbrnr** [comment]
> I started with a fresh venv and did a `pip install` for whatever was raising an import error. Do you think that information would be useful in the documentation?

Could we not put the required dependencies in a dedicated optional dependencies group?

> The bad news is that the tests are broken, but the good news is that the tests are broken. :)
I quickly checked. We are comparing floats for equality, which fails because of rounding errors. I can fix the failing test but I don't have the time to look for all comparisons.

OK, when did this start happening? Let's merge this doc PR once we've clarified how we want to write the instructions, and then maybe just open a new issue for the failing tests?

**Comment by mbillingr** [comment]
> OK, when did this start happening? 

We probably always had them and they occasionally start failing when we update numpy, scipy, or sklearn.


> Could we not put the required dependencies in a dedicated optional dependencies group?

We have neither a requirements.txt nor a pyproject.toml, so I'm not sure where to create a dependency group... actually, I could not find a single dependency specififacion in any of our setup files.
Modernizing the build system is a can of worms I don't want to open right now, but I could add the library versions I used to the doc/README.md. What do you think?

**Comment by mbillingr** [comment]
>  preferably directly in README.md

Done.

**Comment by cbrnr** [comment]
Perfect, thank you so much!

**Pull request merged**
