### PR TITLE
Fix Travis setup

### PR DESCRIPTION
**Pull request by cbrnr**
Trying to fix Travis in this PR...

### CODE REVIEW

**Comment by cbrnr** [comment]
Looks like the old package versions aren't compatible with Python 3.5 anymore. We could use Python 3.4, or we could just test the old versions with Python 2.7.

**Comment by cbrnr** [comment]
I'd go for the current setup:

- Python 2.7 and oldest supported packages
- Python 2.7 with current versions
- Python 3.5 with current versions

Current versions as available in Anaconda. @mbillingr what do you think?

**Comment by cbrnr** [comment]
I've merged this because otherwise our tests are broken which affects all other PRs.

**Comment by mbillingr** [comment]
Ok, this is fine with me :)

**Pull request merged**
