### PR TITLE
Update docs for 0.2

### PR DESCRIPTION
**Pull request by cle1109**
Is this section prominent enough? Where else should we document the changes? What about CHANGELOG (it has been empty so far)?

### CODE REVIEW

**Comment by mbillingr** [comment]
I'd put it in the docs too, but I don't know where it fits (I guess that is because we have so little documentation) :)

At some point in the future we should start to track changes with every pull request like [this](https://github.com/scikit-learn/scikit-learn/blob/master/doc/whats_new.rst).

**Comment by cle1109** [comment]
I agree that our documentation is rather sparse at the moment. I will put a note section right after "Overview" for now. I will create an issue that reminds us to work on the documentation.

Tracking changes of every PR is awesome. For now, I suggest that we keep working with milestones. We can then add all merged PRs from a specific milestone that we deem worthy to the list of changes.

**Comment by cle1109** [comment]
Also, I forget how to build and deploy the doc on the website... Is this documented somewhere?

**Comment by mbillingr** [comment]
I think I wrote it down somewhere...

**Comment by mbillingr** [comment]
... seems to be gone.

If I remember correctly, these are some of the steps:

    cd doc

    # generate automatic api documentation (run after big source file changes)
    ./generate_apidoc.sh  

    # build docs
    python make.py html  # or something like that

    # finally, push output into the scot-doc repository

**Comment by cle1109** [comment]
OK - let me know when we're ready to release 0.2, and I'll update the website (cf #102). Also, is there anything missing in this PR? If not, feel free to merge.

**Comment by mbillingr** [comment]
Have you checked if the resulting API documentation is correct and complete?

**Comment by cle1109** [comment]
I can only check the API doc by building it, right? I'll do that tomorrow.

**Comment by cle1109** [comment]
The doc looks good. We need to change the version to 0.2.0 before I can upload it.

**Comment by mbillingr** [comment]
True :)

**Comment by cle1109** [comment]
Are we ready to release? Can I change the version and merge #113?

**Comment by cle1109** [comment]
Uh oh :-)

**Comment by mbillingr** [comment]
What's wrong?

**Comment by cle1109** [comment]
:-) glad you didn't see that I screwed up rebasing this branch again.

**Comment by mbillingr** [comment]
Oh, actually I saw it but the additional commits didn't strike me as odd :)

**Comment by cle1109** [comment]
OK, that's it, I will stop using PyCharm for git-related stuff. Maybe I'm just too dumb to use the GUI, but it works great using the command line...

**Comment by mbillingr** [comment]
hehe

**Comment by mbillingr** [comment]
Are we done?

**Comment by cle1109** [comment]
Yep. Can you take care of the rest? I didn't change the version number, can you do that for the release?

**Comment by mbillingr** [comment]
Ok

**Pull request merged**
