### PR TITLE
Infomax: Made fixed random seed optional

### PR DESCRIPTION
**Pull request by kazemakase**
This patch makes the forced random seed in Infomax ICA optional.

@cle1109, @jdammers
Does this look good to you?

@dengemann
Maybe this patch is interesting for MNE as well?

### CODE REVIEW

**Comment by kazemakase** [comment]
Because you can use it to pass a different random number generator to the function, set a manual seed, and it seems to be somewhat standard in MNE (I want to keep the difference as small as possible).

**Comment by cle1109** [comment]
But this seed is not used if `force_random_seed=True`, right? I'm just thinking if we could combine these two parameters into one to make it easier for the user.

**Comment by jdammers** [comment]
@cle1109  @kazemakase @dengemann
according to the original implementation of Infomax (matlab version) the randon state is not fixed. The variability of multiple ICA decompositions like in ICASSO cannot be tested in this way.

**Comment by kazemakase** [comment]
@jdammers @dengemann
With the current patch it is now possible to (a) use a seed that depends on the iteration step (like before), (b) use a fixed seed by specifying `random_state`, or (c) not touch the random state at all.

@cle1109 @dengemann
I did not want to touch the `random_state` parameter because I do not know how this parameter is supposed to behave. Furthermore, what if you want to specify a specific RNG *and* force the seed (well, maybe that's too utopic)?

**Comment by dengemann** [comment]
Yes, this is relevant, please make a PR to MNE!

**Comment by kazemakase** [comment]
> Yes, this is relevant, please make a PR to MNE!

In that case I suggest to continue this discussion at a new PR to MNE.

Once it's done, we can simply merge the upstream version into SCoT.

**Comment by dengemann** [comment]
It's most important to have a solud reimplementation of the algo, even if this sacrifices reproducible results. Maybe the fixed random seed is rather a bug. I probably was biased by fastica at that time.

**Comment by dengemann** [comment]
Api wise it should be done via random_state maybe redefine what None will do or allow for a flag 'iterative' or sth like that

**Comment by dengemann** [comment]
Yes

**Comment by cle1109** [comment]
@dengemann this is a good suggestion, that way we only need one parameter. @kazemakase at least for SCoT we could drop the function `check_random_state()` completely and just use the default random generator.

**Comment by kazemakase** [comment]
@cle1109 
I guess we could do that... might be less work than inserting the `check_random_state` function again.

**Comment by cle1109** [comment]
@kazemakase +1 from my side. Depending on the outcome of the discussion over at MNE, we can always pull another version from there later on. For now, I suggest that after removing `check_random_state()` and provided that all tests and Travis succeed, we merge this PR.

**Comment by cle1109** [comment]
Thanks @kazemakase - now let's see if we can close #35 as well.

**Pull request merged**
