### PR TITLE
Unify _construct_var_eqns

### LINKED ISSUE #94: Unify construction of VAR equations
Currently, the functions `_construct_var_eqns` in varbase.py and `_construct_var_eqns_rls` in var.py share a lot of code.

I propose to construct the equations in one place.

There are at least two options:
 1. to have one function that can optionally create equations with and without RLS.
 2. let `_construct_var_eqns_rls` call `_construct_var_eqns` to construct the equations and then pack the RLS part on top.

### PR DESCRIPTION
**Pull request by cle1109**
Fixes #94. @mbillingr, what do you think?

### CODE REVIEW

**Comment by mbillingr** [comment]
LGTM

**Comment by cle1109** [comment]
If you're happy go ahead and merge it.

**Comment by mbillingr** [comment]
I wish the tests would run properly...

**Comment by cle1109** [comment]
Yes, me too. At least the first env passes, which is a good sign. I think it's safe to merge this PR, but we should try to get Travis up and running ASAP. Unfortunately, I have no idea what the problem could be. Did you check the config in other repos (such as mne-python or scikit-learn)?

**Pull request merged**
