### PR TITLE
Multiclass CSP

### PR DESCRIPTION
**Pull request by mbillingr**
It is not clear how to optimally select components in the multiclass case.
This will require some further investigation...

### CODE REVIEW

**Comment by cle1109** [comment]
Recently I modified the CSP implementation in mne-python. We're using `eigh` there because if that fails we know something's wrong. What's wrong with using it here as well?

**Comment by mbillingr** [comment]
I don't know about the eig/eigh thing, here. Maybe this was an old compatibility.

Anyway, I've never finished this multiclass CSP thing. I can't remember into which issue I ran exactly, but there were some conceptual open questions that need to be thought through.

**Comment by cle1109** [comment]
OK - how do we proceed with this PR then? I kind of don't want to have stale PRs hanging around that will probably never be finished. I think it's better to collect ideas in issues.

**Comment by mbillingr** [comment]
Let's close this PR. I've still got the branch in my fork.

**Pull request closed without merging**
